      seqfile = 14_CHS__chalcone_synthase_flavonoids_M7_seq.fasta   * alignment (copy next to this .ctl)
     treefile = 14_CHS__chalcone_synthase_flavonoids_M7_tree.nwk   * tree actually used (pruned/unrooted, next to this .ctl)
      outfile = 14_CHS__chalcone_synthase_flavonoids_M7_results.txt   * raw codeml output
        noisy = 1                           * 0-9: stdout detail
      verbose = 1                           * 1: detailed output
      runmode = 0                           * 0: user tree
      seqtype = 1                           * 1: codons
    CodonFreq = 2                           * 0:Fequal 1:F1x4 2:F3x4 3:F61 4:F1x4MG 5:F3x4MG 6:FMutSel0 7:FMutSel
      estFreq = 0                           * 0: observed frequencies
        ndata = 1                           * number of data sets
        clock = 0                           * 0: no clock
       aaDist = 0                           * 0: equal amino acid distances
        model = 0                           * 0: one omega for all branches; 2: omega per branch group
      NSsites = 7                           * 0:M0 1:M1a 2:M2a 7:M7 8:M8
        icode = 0                           * 0: universal genetic code
        Mgene = 0                           * 0
    fix_kappa = 0                           * 0: kappa estimated
        kappa = 2                           * initial kappa (ts/tv)
    fix_omega = 0                           * 0: omega estimated; 1: omega fixed
        omega = 0.5                         * initial omega (fixed value if fix_omega = 1)
    fix_alpha = 1                           * 1: no gamma rate variation
        alpha = 0                           * 0: no gamma
       Malpha = 0                           * 0
        ncatG = 10                          * categories of the beta distribution (M7/M8)
        getSE = 0                           * 0: no standard errors
 RateAncestor = 0                           * 0: no ancestral reconstruction
   Small_Diff = 5.0e-7                      * convergence criterion
    cleandata = 1                           * 1: remove columns with gaps/ambiguities/stops
  fix_blength = 0                           * 0: ignore branch lengths in tree; 1: use as initial values; 2: fixed
       method = 0                           * 0: simultaneous optimisation
